language: ruby
cache: bundler
dist: trusty
sudo: false
bundler_args: --frozen

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem --version
  - rvm @global do gem uninstall bundler -a -x -V
  - gem install bundler -V
  - rm -f .bundle/config
  - which bundle
  - ls -la /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/
  - bundle --version


rvm:
  - 2.3.5
  - 2.4.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script: bundle exec rake spec

branches:
  only:
  - master
