language: ruby
cache: bundler
dist: trusty
# sudo: false

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem --version
  - rvm @global do gem uninstall bundler -a -x
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config

rvm:
  - 2.3.5
  - 2.4.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script: bundle exec rake spec

branches:
  only:
  - master
